{% set name = "ndbc-api" %}
{% set version = "0.25.10.28.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ndbc_api-{{ version }}.tar.gz
  sha256: 0c12fbd7a782bbd6fe48c5e39c2f49a1de4af8eb21d87638738340ec87b487e0


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }},<3.13
    - requests
    - pandas
    - beautifulsoup4
    - urllib3
    - xarray
    - scipy
    - h5netcdf

test:
  requires:
    - python {{ python_min }}
  imports:
    - ndbc_api

about:
  home: https://github.com/cdjellen/ndbc-api
  summary: A Python API for the National Data Buoy Center.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CDJellen
